### ISSUE TITLE
少了些調整

### ISSUE THREAD

**Issue by jaronemo** [forjason/account_move_adjust#1]
一、要直接pass 掉 分錄的限制。
二、測試完成後要做為整批次 的調整

**Comment by forjason** [comment]
我再补充一点

三、只有币种为台币的，才能进行四舍五入操作。

**Comment by jaronemo** [comment]
那我也在補充一點，
整批次的要 在 filter 內加入 已調、未調（直接做為 SAJ and EXJ 跟幣別的) 的 讓使用者操作快選 -〉 整批

**Comment by forjason** [comment]
除了币别判断，以上几点都已经完成了。
